---

- hosts: all
  become: yes
  tasks:
    - name: centos7 install epel
      yum:
        name: epel-release
        state: present

    - name: centos7 install nginx
      yum:
        name: nginx
        state: present
