---

- hosts: all
  become: yes
  collections:
    - community.mysql
  tasks:
    # - name: centos7 install wget
    #   yum:
    #     name: wget
    #     state: present

    - name: centos7 get&install noarch
      ansible.builtin.shell: sudo rpm -ivh https://mirrors.tuna.tsinghua.edu.cn/mysql/yum/mysql80-community-el7/mysql80-community-release-el7-7.noarch.rpm
      ignore_errors: yes

    - name: centos7 import pubkey
      ansible.builtin.shell: sudo rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

    - name: centos7 install mysql-community-server-8.0.31
      ansible.builtin.yum:
        name: mysql-community-server-8.0.31
        state: present

    - name: start mysql
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Get MySQL version with non-default credentials
      community.mysql.mysql_info:
        login_user: root
        login_password: Asd83915808@
        filter: version

    # - name: Secure MySQL Installation
    #   mysql_user:
    #     name: root
    #     password: Asd83915808@
    #     update_password: on_create        

    # - name: restart mysql
    #   ansible.builtin.service:
    #     name: mysqld
    #     state: restarted