---

- hosts: all
  become: true
  tasks:
    - name: Copy my.cnf
      ansible.builtin.shell: cp /vagrant/vagrant/"{{ ansible_hostname }}".cnf /etc/my.cnf

    - name: Start mysql
      ansible.builtin.systemd:
        name: mysqld
        state: started
        enabled: true

    - name: Get init password
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log
      register: init_password

    - name: Print init_password
      set_fact:
        substring: "{{ init_password.stdout.split(': ')[1].split('\n')[0] }}"

    - name: Debug
      debug:
        msg: "{{ substring }}"

    # - name: Reset MySQL password for 'username'
    #   community.mysql.mysql_user:
    #     name: root
    #     password: Asd83915808@
    #     host: localhost
    #     login_user: root
    #     login_password: "{{ substring }}"
    #     state: present

    # - name: Restart mysql
    #   # 如果是使用Systemd管理的服务，可以使用systemd模块
    #   systemd:
    #     name: mysqld
    #     state: restarted
    #     enabled: true