---

- hosts: all
  become: yes
  tasks:
    # - name: centos7 install wget
    #   yum:
    #     name: wget
    #     state: present

    - name: centos7 get&install noarch
      ansible.builtin.shell: sudo rpm -ivh https://mirrors.tuna.tsinghua.edu.cn/mysql/yum/mysql80-community-el7/mysql80-community-release-el7-7.noarch.rpm
      ignore_errors: yes

    - name: centos7 import pubkey
      ansible.builtin.shell: sudo rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

    - name: centos7 install mysql-community-server-8.0.31
      ansible.builtin.yum:
        name: mysql-community-server-8.0.31
        state: present

    - name: start mysql-community-server-8.0.31
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Secure MySQL Installation
      community.mysql.mysql_user:
        login_user: root
        host_all: yes
        password: Asd83915808@
        update_password: always        